name: Ktlint Check

on: [workflow_dispatch, pull_request]

jobs:
  ktlint:
    name: "Run Ktlint Check"
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v4

      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: "Run Ktlint Check"
        run: ./gradlew ktlintCheck
